name: 'Continuous Integration'

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Agent selection string.'
        required: false
        default: 'ubuntu-latest'
        type: string

permissions:
  id-token: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  continuous-integration:
    name: 'Continuous Integration'
    runs-on: ${{ inputs.runs-on }}
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Check Terraform Format
        run: terraform fmt -check
      - name: Check Terraform Syntax
        run: terraform init && terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Check Terraform Lint
        run: tflint --init && tflint -f compact
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Check Terraform Security (TFsec)
        uses: aquasecurity/tfsec-action@v1.0.3
      - name: Check Terraform Security (Checkov)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
